// <auto-generated />
using System;
using EntityFrameworkCore.TableRelationships;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameworkCore.TableRelationships.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221011143508_BaseMigration")]
    partial class BaseMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("EntityFrameworkCore.TableRelationships.Pessoa", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("EntityFrameworkCore.TableRelationships.Tarefa", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PessoaIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.HasIndex("PessoaIdentifier");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("EntityFrameworkCore.TableRelationships.Tarefa", b =>
                {
                    b.HasOne("EntityFrameworkCore.TableRelationships.Pessoa", null)
                        .WithMany("Tarefas")
                        .HasForeignKey("PessoaIdentifier");
                });

            modelBuilder.Entity("EntityFrameworkCore.TableRelationships.Pessoa", b =>
                {
                    b.Navigation("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
